- name: Influxdb Setup
  hosts: localhost
  tasks:
      - name: Restarting sshd
        shell: "sed -i 's/#Match User anoncvs/ForceCommand echo Please wait until the installation is completed..../g' /etc/ssh/sshd_config && systemctl restart sshd"

      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes

      - name: Configuring GPG key and adding Repo
        shell: "{{ item }}"
        with_items:
          - wget -q https://repos.influxdata.com/influxdata-archive_compat.key
          - echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
          - echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
          - rm -rf /root/influxdata-archive_compat.key

      - name: Remove the key file
        file:
          path: /root/influxdata-archive_compat.key
          state: absent

      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes

      - name: Installing influxdb
        apt:
          name: influxdb2
          state: latest

      - name: Enable influxdb
        ansible.builtin.systemd:
          name: influxdb
          state: started
          enabled: true

      - name: Getting the status of the service
        shell: systemctl status influxdb | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - name: Creating a directory for shell script
        ansible.builtin.file:
          path: /opt/cloudstack
          state: directory         
          
      - name: Copy files for shell script
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/usr/local/src/influxdb-22-04/opt/cloudstack/cleanup.sh', confdest: '/opt/cloudstack/'}     

      - name: Adding a line for shell script
        lineinfile:
          path: /root/.bashrc
          line: "chmod +x /opt/cloudstack/cleanup.sh && /opt/cloudstack/cleanup.sh"
          state: present      
          
      - name: Restarting sshd
        shell: "sed -i 's/ForceCommand echo Please wait until the installation is completed..../#Match User anoncvs/g' /etc/ssh/sshd_config && systemctl restart sshd"